version: '3'
services:
  samba:
    image: dperson/samba
    container_name: samba
    command: -g "log level = 2" -u "raspberry;raspberry" -s "share;/share;yes;no;no;raspberry"
    ports:
    - 139:139
    - 445:445
    volumes:
    - $MEDIA/usb:/share
    environment:
    - USERID:1000
    - GROUPID:1000
