version: '3'
services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    command: -g "log level = 2" -u "raspberry;raspberry" -s "share;/share;yes;no;no;raspberry" -s "ssd;/ssd;yes;no;no;raspberry"
    ports:
    - 139:139
    - 445:445
    volumes:
    - /media/usb:/share
    - /media/ssd:/ssd
    environment:
    - USERID:1000
    - GROUPID:1000
